name: Container Image Builds

on:
  push:
    branches: [ oldstable ]
    tags: ["v*"]
  workflow_dispatch:


jobs:
  images:
    name: Build and upload container images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Gather container image tags
        id: container
        uses: greenbone/actions/container-image-tags@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # for the current oldstable release the extension functions are
      # contained in gvmd, so only a simplified Docker image is needed
      - name: Build and push Container image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: greenbone/pg-gvm:oldstable
          file: .docker/oldstable.Dockerfile
          platforms: linux/amd64,linux/arm64
          labels: |
            org.opencontainers.image.vendor=Greenbone
            org.opencontainers.image.revision=${{ github.sha }}
